DROP TABLE TEST.USERS;
DROP TABLE TEST.USER_ROLE;

CREATE TABLE USERS (ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 501, INCREMENT BY 1), USER_ID varchar(45) NOT NULL, USER_NAME varchar(45) NOT NULL, PASSWORD varchar(20) NOT NULL, EMAIL varchar(100) NOT NULL);

CREATE TABLE USER_ROLE (USER_ID varchar(45), ROLE varchar(20));

INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, EMAIL) VALUES('jainnshi', 'SHISHIR JAIN', 'shishir', 'jainshi@gmail.com');

INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, EMAIL) VALUES('survesac', 'SACHIN SURVE', 'sachin', 'sachinsurve@gmail.com');

INSERT INTO USER_ROLE (USER_ID, ROLE) VALUES ('jainnshi', 'ROLE_USER');

INSERT INTO USER_ROLE (USER_ID, ROLE) VALUES ('survesac', 'ROLE_USER');