DROP TABLE USERS;
DROP TABLE USER_ROLE;

CREATE TABLE USERS (
	ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 501, INCREMENT BY 1), 
	USER_ID varchar(45) NOT NULL, 
	USER_NAME varchar(45) NOT NULL, 
	PASSWORD varchar(20) NOT NULL, 
	EMAIL varchar(100) NOT NULL
);

CREATE  TABLE LOGIN_USER (
  USER_ID VARCHAR(45) NOT NULL ,
  PASSWORD VARCHAR(45) NOT NULL ,
  ENABLED smallint NOT NULL DEFAULT 1 ,
  PRIMARY KEY (USER_ID));
 
CREATE TABLE USER_ROLES (
  ID int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), 
  USER_ID VARCHAR(45) NOT NULL,
  ROLE_ID smallint NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE (ROLE_ID, USER_ID),
  --KEY fk_userid_idx (USER_ID),
  CONSTRAINT fk_userid FOREIGN KEY (USER_ID) REFERENCES LOGIN_USER (USER_ID)
);


INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, EMAIL) VALUES('jainnshi', 'SHISHIR JAIN', 'shishir', 'jainshi@gmail.com');

INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, EMAIL) VALUES('survesac', 'SACHIN SURVE', 'sachin', 'sachinsurve@gmail.com');

INSERT INTO USERS (USER_ID, USER_NAME, PASSWORD, EMAIL) VALUES('nirvemil', 'Milind Nirve', 'milind', 'milindnirve@gmail.com');


INSERT INTO LOGIN_USER (USER_ID, PASSWORD) VALUES('jainnshi', 'shishir');

INSERT INTO LOGIN_USER (USER_ID, PASSWORD) VALUES('survesac', 'sachin');

INSERT INTO LOGIN_USER (USER_ID, PASSWORD) VALUES('nirvemil', 'milind');


INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES ('jainnshi', 0);
INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES ('jainnshi', 1);

INSERT INTO USER_ROLES (USER_ID, ROLE_ID) VALUES ('survesac', 0);